### ISSUE TITLE
When entering a nether portal in the nether, it created a new portal on the surface, 300 blocks away from entry portal

### ISSUE THREAD

**Issue by Minithra** [Wizelf402/Permafrost#17] opened 2021-06-05 17:23 UTC
Pack version 1.1.6. 

Made a nether portal in my nice cave home, gathered some materials, tried to go back home, new portal appeared on the surface, I had no chance to get to my home in the blizzard.

**Comment by NevadaActual** [comment] 2021-06-05 21:22
Can you provide a world download? I know vanilla portal mechanics are a screwy mess requiring a maths degree to understand, so unless I can reproduce it I'll have to chalk it up to vanilla being vanilla.

**Comment by Minithra** [comment] 2021-06-05 21:55
[1_1_6 - 2.zip](https://github.com/Wizelf402/Permafrost/files/6603283/1_1_6.-.2.zip)

Hopefully the world still works, I had to kill the process after it froze on me, haven't tried to start it after.

**Comment by NevadaActual** [comment] 2021-06-05 21:57
Ah, I bet you an Apotheosis crash happened at the same time, that's the thing that causes process freezing. Thank you, I'll test this ASAP.

**Comment by Minithra** [comment] 2021-06-05 21:59
To clarify, I did keep playing after the portal stuff, just turned on KeepInventory and didn't go back to the nether. I also added One Probe, hopefully it's not that that's breaking things, because the F3 screen is just massively crowded now and I don't recognize the new ores :D

**Comment by NevadaActual** [comment] 2021-06-05 22:01
Should be fine, I'll just see if I have any issue *returning* from the nether, since that's the main issue to address. Crashing and freezing will be eliminated (mostly) with the bugfix coming out.

**Comment by NevadaActual** [comment] 2021-06-05 22:13
Okay, I'm fairly certain it was vanilla minecraft mechanics. You can move the portal over 20ish blocks in the nether, and it works properly again. Specifically, move it to -24 [whatever y] 17, and you'll have a two way portal again. I'll close the issue, but feel free to @me on the discord if you want me to walk you through the process.

**Closed as completed by NevadaActual** 2021-06-05 22:13 UTC
Labels: wontfix
