### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by MechaJ** [Wizelf402/Permafrost#3] opened 2021-06-02 08:07 UTC
Modpack version 1.1.3
[crash-2021-06-02_03.02.02-server.txt](https://github.com/Wizelf402/Permafrost/files/6583048/crash-2021-06-02_03.02.02-server.txt)

**Comment by rinOfTheStars** [comment] 2021-06-02 18:53
Looks to be caused by apotheosis trying to spawn a boss and failing?

**Comment by NevadaActual** [comment] 2021-06-03 23:49
As this issue was created before 1.1.6 I'm going to close it, as that version resolves many of the Apotheosis related crashes and bugs. If you have similar issues post 1.1.6, respond to this issue so we can open it again.

(We're overhauling the repo, due to updates before release 1.2 being extremely unstable. Give us a day or two, and we'll have bug templates ready for use.)

**Closed as completed by NevadaActual** 2021-06-03 23:49 UTC
