### ISSUE TITLE
Soulbond is broken

### ISSUE THREAD

**Issue by jkieberking** [Wizelf402/Permafrost#29] opened 2021-06-14 00:54 UTC
Soulbound seems to malke an item dissapear

version 1.3, soulbound diamond chestplate

when you die the chestplate isn't on your body when you respawn, and it isn't in your grave when you get the items back

**Comment by NevadaActual** [comment] 2021-06-19 21:47
Soulbound appears to delete the item from the world, while Soulbinding works as intended. I will ask Wiz to disable the non-working enchant ASAP.

**Comment by NevadaActual** [comment] 2021-06-20 19:14
Fix has been found, and will be implemented in the next version.

**Closed as completed by NevadaActual** 2021-06-20 19:14 UTC
Labels: bug
