### ISSUE TITLE
Quark Wraith does not appear to spawn. Lost City Chests spawn Empty.

### ISSUE THREAD

**Issue by moonbeast32** [Wizelf402/Permafrost#32] opened 2021-06-20 00:41 UTC
1: Bees are unresponsive. I placed a hive, I used one of the bee spawn eggs given by the quest book, and I placed down flowers near the hive. The bee flew into the hive, and has never exited since. I have tried different flowers, different lighting, and all else I know about. The bee never collects honey or makes honeycomb. It just remains in the hive and never leaves.

2: Soulbound vs Soulbinding. The quest book awards the player with a "soulbinding" enchanted book. This book can also be found in dungeon chests and etc. According to JEI, "soulbinding" is distinct from "soulbound," and only "soulbound" can be applied to items whereas "soulbinding" can not. I don't know if this is due to my own lack of understanding of enchantment mechanics, but isn't there usually a message that displays telling you the reason why a given enchantment cannot be applied? I see no such message.

3: Water bottles do not collect water. When I right click a water source block with a water bottle, the bottle briefly disappears as I would normally expect it to when filling with water, but nothing happens. No filled bottle appears in my inventory, nor does the empty glass bottle get removed. I have not tried using a cauldron yet, but I expect the result to be the same. Unless I am missing something, This issue renders potion-making impossible without cheating.

4: Mob spawn rates. Now I do not know if this is a bug, intentional design, or my own bad luck, but I rarely ever see mobs in the overworld that aren't the chilled or vanilla monsters. I can count on one hand the amount of times I have seen something from Alex's Mobs or I&F spawn. Aside from that, I have never seen anything from Mowzie's mobs or Quark (with the exception of foxhounds). Once again, I don't know if that is by design, but some of those mobs are required for progression in the quest book. The Quark wraith, for example has never spawned in the overworld or nether. I have also never encountered any pillagers that have spawned naturally outside of underground spawners. 

5: Empty treasure chests. So far, I have only encountered this issue in one of the Lost Cities structures. There are a few times when I approach a spot where a treasure chest should be, but there is nothing there. After a few seconds, the chest will suddenly appear, but it will be empty when I check it. I don't know how to check tile data, so I don't know what should have been inside it.

**Comment by NevadaActual** [comment] 2021-06-20 19:13
1. Bees are a singular issue that we're still puzzling out. We'll either create a custom mod to let them work, or use some other solution, but it's rather low priority compared to some other issues.
2. Duplicate of #29
3. Talked about this in the Discord, but it's a forge click handling issue. You have to click on water _without_ hitting the block behind it, or use a bucket to put it in a cauldron. We legitimately can't fix it, until we figure out the specifics.
4. It's only supposed to monsters. Completely intentional by design, and frozen pigs still spawn sometimes. The wraith is not spawning, I've noticed it too in my own testing, so I'll make this issue about that bug specifically.
5. This is a weird one. Are you positive you're playing the most recent version? The lost cities usually don't have that much loot, but none is excessive. With how rare they are it's not a huge priority, but it hurts from a player standpoint so we'll bump it up a bit.

Appreciate the reporting, thank you kindly. Do try and make sure bugs aren't a duplicate in the future, or even better make sure to make a separate issue for each bug so we can address each individually.

**Comment by NevadaActual** [comment] 2022-06-21 00:23
Calling this addressed, all issues have been fixed in the last year.

**Closed as completed by NevadaActual** 2022-06-21 00:23 UTC
Labels: bug, needs testing
