### ISSUE TITLE
Suggest QOL changes to the Quest Book here!

### ISSUE THREAD

**Issue by rinOfTheStars** [Wizelf402/Permafrost#13] opened 2021-06-04 04:11 UTC
What the title says basically. Theres probably a lot of small things in the quest book that could use some tweaks to make them better, suggest them here. **Non serious replies will be removed/ignored.**

**Comment by NevadaActual** [comment] 2021-06-04 04:54
To elaborate a tad, by QOL we mean changes to the _**core function**_ of the quest book. The order of quests, the difficulty of quests, and so on. _**Bugs**_ with quests should be made a separate issue, so they can be assessed for the next bug fix update. Any QOL changes will be delayed until the next minor or major content update, barring unusual circumstances.

**Comment by NevadaActual** [comment] 2021-06-04 05:17
The Fishing quest, which requires three of each fish, is situated as (one of the three) quest 2(s) of the entire book. Disregarding how little value fish offer early on, the ability to deal with cold is **extremely** low in the early game, making diving for fish near impossible. Changing this quest to be an optional side quest would be the better option, or maybe swap it was a later quest that ensures the player is past the early game before presenting itself.

**Comment by rinOfTheStars** [comment] 2021-06-04 05:38
Do note that fishing is possible with a fishing rod underground in a fishing pool, though at drastically lowered speed then surface fishing or diving.
Perhaps make the quest check for a fishing rod of any durability and 1 of any fish (forge probably has an item tag for that!)?

**Comment by MechaJ** [comment] 2021-06-05 11:41
My suggestion would be moving the information regarding the death totem and how to grow crops to be more immediately available, perhaps revealing the greenhouse quest immediately after the campfire quest. I have to admit I wasted more than a bit of time from my first farm not being deep enough nor with sunlight, even tried using lava and campfires to heat up the farm, haha.

**Comment by NevadaActual** [comment] 2021-06-05 21:24
@MechaJ Greenhouse and plant growing mechanics are going to see some changes for 1.2, so we'll definitely reword the descriptions of the process to match. Thank you for the feedback!
(Glass **directly** over the plant so it can see the sky lets it grow. That's only for surface level, though, I don't know how deep plants have to be to reproduce the effect.)

**Comment by NevadaActual** [comment] 2021-06-06 01:25
Make mention of the ice elemental's sounds somewhere in the book, along with their inordinate ability to aggro from a long distance.

**Comment by XDGrangerDX** [comment] 2021-06-11 16:20
[02:47] ItsLexa!: proposal: shift around the botania quests to say that your first step is botanical fertilizer, made from mushrooms
[02:47] ItsLexa!: then ask the player to collect a white flower
[02:48] ItsLexa!: thats far far easier and more reliable than trying to find a damn white mushroom

[02:54] ItsLexa!: if the previous proposal is accepted you'll need to make a mortar and pestle, which will leave you with 2 bowls with no use. Might aswell make them useful.(edited)
[03:00] ItsLexa!: you could, theoretically, even get rid of cave roots entirely, and tell people to live off the mushrooms, but be careful with that because if you happen to spawn somewhere without sand around you'll be unable to get farmable foods for quite a while, potentially depriving players of food eventually unless they make far trips for new mushrooms
[03:00] ItsLexa!: might be a bit too hardcore

[02:52] ItsLexa!: also i think a quest pointing out that these mushrooms are edible would be a good idea, too
[02:52] ItsLexa!: mushroom stew
[02:53] ItsLexa!: ofc everyone hates unstackable food items but yknow, that early game you'll take anything

**Comment by NevadaActual** [comment] 2022-06-21 00:25
Closing, many changes will be made to the quest book by myself in the next [time amount here]. Balancing will happen eventually(tm).

**Closed as completed by NevadaActual** 2022-06-21 00:25 UTC
Labels: inquiry
