### ISSUE TITLE
Bookshelves disappear when placed around enchanting table. 

### ISSUE THREAD

**Issue by willibar17** [Wizelf402/Permafrost#19] opened 2021-06-05 19:18 UTC
I made bookshelves, in a stack of 4 i began placing them, the whole stack disappeared from my inventory.  it wasnt a bugged inventory as i moved all my items around and refilled every slot.

**Comment by NevadaActual** [comment] 2021-06-05 21:18
I'll take a took today, see if I can reproduce the bug. Have you been able to place bookshelves normally since then?

**Comment by NevadaActual** [comment] 2021-06-06 00:12
Tested, couldn't successfully reproduce. If we don't get further details from @willibar17 in the next day or two, I'll mark this as closed.

**Comment by willibar17** [comment] 2021-06-06 01:07
In that whole playthough it was bugged like that. I stopped trying because they are expensive to make

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 5, 2021 at 6:12 PM, ***@***.***> wrote:   


Tested, couldn't successfully reproduce. If we don't get further details from @willibar17 in the next day or two, I'll mark this as closed.

**Comment by NevadaActual** [comment] 2021-06-06 01:18
Additional info was found from the discord, it has something to do with HQM block placing detection. I'd suggest using commands to force complete the quest requiring placed bookshelves, or waiting until the next bugfix patch where we remove the objectives in favor of detection tasks.

**Comment by NevadaActual** [comment] 2021-06-06 01:19
Don't know the timeframe on that aforementioned patch, so the first option is preferable. Let me know if that fixes the issue for you, if not we'll investigate further.

**Comment by willibar17** [comment] 2021-06-06 02:19
That's great to hear thank you 

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 5, 2021 at 7:19 PM, ***@***.***> wrote:   


Don't know the timeframe on that aforementioned patch, so the first option is preferable. Let me know if that fixes the issue for you, if not we'll investigate further.

**Comment by NevadaActual** [comment] 2021-06-06 17:58
Fixed with 1.2.

**Closed as completed** 2021-06-06 17:58 UTC
Labels: question, needs testing
